### ISSUE TITLE
Sync only selected folders

### ISSUE THREAD

**Issue by userhooke** [MStadlmeier/drivesync#1]
Hi!
Is that possible to sync only selected folders/files?
Thank you in advance!

**Comment by MStadlmeier** [comment]
Hey
This will be simple to do in the next update, which will include a "whitelist" option. It should hopefully be out within the next two weeks along with some other improvements.

**Comment by MStadlmeier** [comment]
@userhooke Whitelisting is now available with patch 1.3.0. Enjoy
