### ISSUE TITLE
Partial sync

### ISSUE THREAD

**Issue by amilino** [MStadlmeier/drivesync#12]
Is this supporting partial sync of folders?

**Comment by MStadlmeier** [comment]
Do you mean syncing only specific folders/files? That's possible using the WhiteList / BlackList configuration option. run `ruby drivesync.rb config` or edit the config file `~/.drivesync/config.yml` . The options are explained there in the comments.

**Comment by ETHANWEEGEE** [comment]
That works for me, thanks!
