### ISSUE TITLE
Symlinked directory doesn't sync

### ISSUE THREAD

**Issue by MunifTanjim** [MStadlmeier/drivesync#14]
I've the following symlinked directory:

```
[munif:~/data/Drive] $ ls -l
lrwxrwxrwx 1 munif munif   33 Oct 26 14:03 documents -> /home/ubuntu/munif/data/documents
```

`/home/ubuntu/munif/data/documents` directory has many files and folders inside it.

I created  an empty folder named `documents` on my Google Drive.

When I run `drivesync`, nothing happens.

Dropbox's Linux client follows symlinks. It'd be nice to have this feature in DriveSync.

**Comment by MStadlmeier** [comment]
Resolved by #15
