### ISSUE TITLE
Git clone not allowed

### ISSUE THREAD

**Issue by Fabian42** [MStadlmeier/drivesync#17]
I had to setup my system new, installed `git` (Ruby was already installed) and did `git clone git@github.com:MStadlmeier/drivesync.git`. The result was:

```Cloning into 'drivesync'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by MStadlmeier** [comment]
As this is a public repository, there can't be any issues regarding authentication. I guess there is something wrong with your rsa keys (do you have the correct permissions on your .ssh folder and private key?)

You can definitely clone the repository using https as a workaround, though

    git clone https://github.com/MStadlmeier/drivesync.git

**Comment by teozkr** [comment]
Bit of a necro, but SSH access requires you to generate a SSH keypair (`ssh-keygen -t ed25519`) and upload the public key (`~/.ssh/id_ed25519.pub`) in [your account settings](https://github.com/settings/keys). If you only need read-only access then you should probably clone over HTTPS instead.

This is generic for all GitHub-hosted repos (and most Git hosts in general), and has nothing to do with this repo in particular.
