### ISSUE TITLE
NoMethodError in synchronizer.rb

### ISSUE THREAD

**Issue by thomasaiman** [MStadlmeier/drivesync#2]
I'm running from the bundled package. When I first manually ran the program it did sync some files to my local directory, then appeared to stop after a few minutes. I ran it manually again and got the following output:

 $ ./drivesync

`Local folder is 1576 files behind and 0 files ahead of remote`
`Starting sync at 2017-12-04 18:51:39 -0600`
`/home/thomas/Downloads/drivesync-linux-x86_64-v_1.2/lib/app/src/synchronizer.rb:127:in 'block in sync': undefined method '[]' for nil:NilClass (NoMethodError)`
`    from /home/thomas/Downloads/drivesync-linux-x86_64-v_1.2/lib/app/src/synchronizer.rb:124:in 'each'`
`    from /home/thomas/Downloads/drivesync-linux-x86_64-v_1.2/lib/app/src/synchronizer.rb:124:in 'sync'`
`    from /home/thomas/Downloads/drivesync-linux-x86_64-v_1.2/lib/app/src/synchronizer.rb:228:in 'run'`
`    from /home/thomas/Downloads/drivesync-linux-x86_64-v_1.2/lib/app/drivesync.rb:4:in '<main>'`

**Comment by MStadlmeier** [comment]
@thomasaiman My guess is that you cancelled it prematurely, causing the manifest to not be written properly. If you delete the manifest file: ``rm /home/thomas/.drivesync_manifest`` as well as your local Drive folder and start the program again, it should work fine. It might take a while to download larger files, so be patient. DriveSync will output something when it's done with the sync.
