### ISSUE TITLE
cannot load such file -- rubygems.rb

### ISSUE THREAD

**Issue by pranav-dahiya** [MStadlmeier/drivesync#20]
I am running Arch Linux. Whenever I try to run drivesync I get the following error

```
Traceback (most recent call last):
	1: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
<internal:gem_prelude>:2:in `require': cannot load such file -- rubygems.rb (LoadError)

```

**Comment by MStadlmeier** [comment]
@4n0nym0u5-98 Sounds like a problem with your Ruby installation. Can you run other Ruby software successfully? I would try reinstalling Ruby
