### ISSUE TITLE
Google thirdy part app not secure

### ISSUE THREAD

**Issue by mardif** [MStadlmeier/drivesync#29]
Hi, 
I'm using your very userful tool for backup my database dumps into the gdrive space.
Starting from 1 month, it seems that nothing works 'cause "authorization denied".
I checked into the Google Account, and I see that "enable not secure app" was disabled.
I reactivated it, but when I try to obtain a new token, Google says me that it's not possible.
Do you know something about it? Is there a chance to use your tool with "secure app" feature?

Thanks,
Mariano

**Comment by dmarcondes** [comment]
I am having the same problem

**Comment by MStadlmeier** [comment]
It seems that DriveSync failed the verification process because Google assumes that I own the domain drivesync.com and have not verified it. I will fix this ASAP and get back to you.

**Comment by bobdschingis** [comment]
thanks for the info:-)
I think the message from google during the first time verification with the produced link is also related to this fact. Or am i wrong?

"Die Anmeldung mit Google ist für diese App vorübergehend deaktiviert
Die Verwendung von Google Log-in wurde für diese App noch nicht bestätigt."

**Comment by MStadlmeier** [comment]
@bobdschingis Correct. Apparently no new users can use OAuth for this project until it is verified. So I'm currently going through the nightmare that is the Google Developer Console, trying to get the project verified.

**Comment by Caballerog** [comment]
Thanks for your help!

I'm waiting for news =)

**Comment by peepingThomist** [comment]
I'm excited to use this program for the first time. Good luck with the red tape!

**Comment by MStadlmeier** [comment]
I just re-submitted the app, so I hope the issue will be resolved in the next few days. Thanks for your patience.

**Comment by MStadlmeier** [comment]
@mardif @Caballerog @peepingThomist @dmarcondes @bobdschingis The project is verified now and the issue should be resolved :)

**Comment by bobdschingis** [comment]
Thank you very much for your work. :-)
Guden Rutsch! ;-)
