### ISSUE TITLE
can't reauthorize Google Drive access 

### ISSUE THREAD

**Issue by thomasaiman** [MStadlmeier/drivesync#3]
From drive.google.com, settings > manage apps > drivesync > disconnect from drive.
Natually, drivesync no longer has access to my account, but I don't see any way to request that authorization again.

**Comment by MStadlmeier** [comment]
@thomasaiman If you delete ~/.credentials/drivesync.yaml DriveSync should prompt you to re-authorize. I'll make this easier and more obvious in the next version.
