### ISSUE TITLE
Not sync shared drive

### ISSUE THREAD

**Issue by redzuk** [MStadlmeier/drivesync#43]
If google drive has additional shared drives his not synced.
Synced only files in MyDrive folder.

**Comment by MStadlmeier** [comment]
@redzuk Check out the `sync_shared_in_drive` option in the config file.

**Comment by redzuk** [comment]
cat config.yml | grep sync_shared_in_drive
sync_shared_in_drive: true

But additional shared drives not synced.
Synced only files in MyDrive folder.

**Comment by MStadlmeier** [comment]
I'm not sure which additional files you mean but you have to add shared files to your drive in order for them to be managed by drivesync. There should be a button for that on any shared Drive link.On Aug 26, 2020 23:34, redzuk <notifications@github.com> wrote:
cat config.yml | grep sync_shared_in_drive
sync_shared_in_drive: true
But additional shared drives not synced.
Synced only files in MyDrive folder.

**Comment by redzuk** [comment]
I mean something like this https://imgur.com/3oW5jk5.
Imposible syncing files whis aditional shared disk?
